GitHub Actions ScriptCopy
netspaker_scan_job;
    runs-on: ubuntu-20.04
      - name: Start Netsparker Enterprise Scan
        uses: netsparker/Netsparker-Cloud-GitHub-Actions@v0.0.1
        id: netsparker-enterprise-scan-step
        with:
          website-id: '550d0c3e-e0e1-402d-6b5d-ad1801cd165f'
          scan-type: 'FullWithPrimaryProfile'
          profile-id: '00000000-0000-0000-0000-000000000000'
          user-id:secrets.de8d4f9b7f914621a3b3acdb01f8e690
          api-token:R/KPlKlBKvRuW6zny525Nf1EJbJpSswyLZSkRmM6OF0=
          base-url: 'https://www.netsparkercloud.com'
      # Displays output for action
